model:
  type: "logistic_regression"
  parameters:
    random_state: 42
    max_iter: 1000
    solver: "liblinear"

training:
  test_size: 0.2
  validation_split: 0.1
  cross_validation_folds: 5

data:
  feature_columns:
    - "age"
    - "tenure_months" 
    - "monthly_charges"
    - "total_charges"
  target_column: "target"
  
deployment:
  min_accuracy_threshold: 0.75
  min_precision_threshold: 0.70
  min_recall_threshold: 0.65
  performance_window: "7d"
  
monitoring:
  drift_threshold: 0.1
  alert_email: "ml-team@company.com"
  check_interval: "1h"
